/**
 * Official Tools Index
 * Feature: 016-hero-tool-search
 *
 * Static index of all official tools for client-side search.
 * Searchable by name (translated), description (translated), and platform.
 */

import { OfficialTool } from "@/types/search";
import { Platform } from "@/types";

/**
 * Complete index of all official tools.
 * The nameKey and descriptionKey reference translation keys.
 */
export const OFFICIAL_TOOLS: OfficialTool[] = [
    // ============================================================================
    // TikTok Tools
    // ============================================================================
    {
        id: "tiktok-script-writer",
        name: "TikTok Script Writer",
        nameKey: "scriptWriter.title",
        description: "Create scripts so good your FYP will thank you",
        descriptionKey: "scriptWriter.description",
        platform: "tiktok",
        href: "/tiktok/script-writer",
        icon: "🎵",
        dateAdded: "2024-01-01",
        popularity: 86,
        featured: true,
        language: "en",
        tags: ["tiktok", "script", "writer", "scripts", "good"],

    },
    {
        id: "tiktok-video-ideas",
        name: "TikTok Video Ideas",
        nameKey: "videoIdeas.title",
        description: "Get viral video ideas for TikTok",
        descriptionKey: "videoIdeas.description",
        platform: "tiktok",
        href: "/tiktok/video-ideas",
        icon: "🎵",
        dateAdded: "2024-01-01",
        popularity: 92,
        featured: true,
        language: "en",
        tags: ["tiktok", "video", "ideas", "viral"],

    },
    {
        id: "tiktok-hook-generator",
        name: "TikTok Hook Generator",
        nameKey: "hookGenerator.title",
        description: "Generate hooks that stop the scroll",
        descriptionKey: "hookGenerator.description",
        platform: "tiktok",
        href: "/tiktok/hook-generator",
        icon: "🎵",
        dateAdded: "2024-01-01",
        popularity: 86,
        featured: true,
        language: "en",
        tags: ["tiktok", "hook", "generator", "hooks", "stop"],

    },
    {
        id: "tiktok-hashtag-generator",
        name: "TikTok Hashtag Generator",
        nameKey: "hashtagGenerator.title",
        description: "Find the best hashtags for your videos",
        descriptionKey: "hashtagGenerator.description",
        platform: "tiktok",
        href: "/tiktok/hashtag-generator",
        icon: "🎵",
        dateAdded: "2024-01-01",
        popularity: 91,
        featured: true,
        language: "en",
        tags: ["tiktok", "hashtag", "generator", "best", "hashtags"],

    },
    {
        id: "tiktok-username-generator",
        name: "TikTok Username Generator",
        nameKey: "usernameGenerator.title",
        description: "Generate unique usernames for TikTok",
        descriptionKey: "usernameGenerator.description",
        platform: "tiktok",
        href: "/tiktok/username-generator",
        icon: "🎵",
        dateAdded: "2024-01-01",
        popularity: 92,
        featured: false,
        language: "en",
        tags: ["tiktok", "username", "generator", "unique", "usernames"],

    },
    {
        id: "tiktok-bio-generator",
        name: "TikTok Bio Generator",
        nameKey: "tiktokBioGenerator.title",
        description: "Create an engaging TikTok bio",
        descriptionKey: "tiktokBioGenerator.description",
        platform: "tiktok",
        href: "/tiktok/bio-generator",
        icon: "🎵",
        dateAdded: "2024-01-01",
        popularity: 93,
        featured: false,
        language: "en",
        tags: ["tiktok", "bio", "generator", "engaging"],

    },
    {
        id: "tiktok-caption-generator",
        name: "TikTok Caption Generator",
        nameKey: "captionGenerator.title",
        description: "Generate captions for your TikTok videos",
        descriptionKey: "captionGenerator.description",
        platform: "tiktok",
        href: "/tiktok/caption-generator",
        icon: "🎵",
        dateAdded: "2024-01-01",
        popularity: 95,
        featured: false,
        language: "en",
        tags: ["tiktok", "caption", "generator", "captions"],

    },
    {
        id: "tiktok-coins-calculator",
        name: "TikTok Coins Calculator",
        nameKey: "coinsCalculator.title",
        description: "Calculate TikTok coins value",
        descriptionKey: "coinsCalculator.description",
        platform: "tiktok",
        href: "/tiktok/coins-calculator",
        icon: "🎵",
        dateAdded: "2024-01-01",
        popularity: 88,
        featured: false,
        language: "en",
        tags: ["tiktok", "coins", "calculator", "calculate"],

    },
    {
        id: "tiktok-money-calculator",
        name: "TikTok Money Calculator",
        nameKey: "moneyCalculator.title",
        description: "Estimate earnings from TikTok",
        descriptionKey: "moneyCalculator.description",
        platform: "tiktok",
        href: "/tiktok/money-calculator",
        icon: "🎵",
        dateAdded: "2024-01-01",
        popularity: 88,
        featured: false,
        language: "en",
        tags: ["tiktok", "money", "calculator", "estimate", "earnings"],

    },
    {
        id: "tiktok-engagement-calculator",
        name: "TikTok Engagement Calculator",
        nameKey: "engagementCalculator.title",
        description: "Calculate your engagement rate",
        descriptionKey: "engagementCalculator.description",
        platform: "tiktok",
        href: "/tiktok/engagement-calculator",
        icon: "🎵",
        dateAdded: "2024-01-01",
        popularity: 85,
        featured: false,
        language: "en",
        tags: ["tiktok", "engagement", "calculator", "calculate"],

    },
    {
        id: "tiktok-ad-copy-generator",
        name: "TikTok Ad Copy Generator",
        nameKey: "tiktokAdCopyGenerator.title",
        description: "Generate ad copy for TikTok campaigns",
        descriptionKey: "tiktokAdCopyGenerator.description",
        platform: "tiktok",
        href: "/tiktok/ad-copy-generator",
        icon: "🎵",
        dateAdded: "2024-01-01",
        popularity: 94,
        featured: false,
        language: "en",
        tags: ["tiktok", "copy", "generator"],

    },
    {
        id: "tiktok-shop-name-generator",
        name: "TikTok Shop Name Generator",
        nameKey: "shopNameGenerator.title",
        description: "Generate creative shop names",
        descriptionKey: "shopNameGenerator.description",
        platform: "tiktok",
        href: "/tiktok/shop-name-generator",
        icon: "🎵",
        dateAdded: "2024-01-01",
        popularity: 85,
        featured: false,
        language: "en",
        tags: ["tiktok", "shop", "name", "generator", "creative"],

    },
    {
        id: "tiktok-thumbnail-text-generator",
        name: "TikTok Thumbnail Text Generator",
        nameKey: "tiktokThumbnailTextGenerator.title",
        description: "Generate text overlays for thumbnails",
        descriptionKey: "tiktokThumbnailTextGenerator.description",
        platform: "tiktok",
        href: "/tiktok/thumbnail-text-generator",
        icon: "🎵",
        dateAdded: "2024-01-01",
        popularity: 86,
        featured: false,
        language: "en",
        tags: ["tiktok", "thumbnail", "text", "generator"],

    },
    {
        id: "tiktok-content-calendar-generator",
        name: "TikTok Content Calendar",
        nameKey: "tiktokContentCalendarGenerator.title",
        description: "Plan your TikTok content calendar",
        descriptionKey: "tiktokContentCalendarGenerator.description",
        platform: "tiktok",
        href: "/tiktok/content-calendar-generator",
        icon: "🎵",
        dateAdded: "2024-01-01",
        popularity: 90,
        featured: false,
        language: "en",
        tags: ["tiktok", "content", "calendar", "plan"],

    },
    {
        id: "tiktok-song-recommendations",
        name: "TikTok Song Recommendations",
        nameKey: "tiktokSongRecommendations.title",
        description: "Find trending songs for your videos",
        descriptionKey: "tiktokSongRecommendations.description",
        platform: "tiktok",
        href: "/tiktok/song-recommendations",
        icon: "🎵",
        dateAdded: "2024-01-01",
        popularity: 93,
        featured: false,
        language: "en",
        tags: ["tiktok", "song", "recommendations", "trending", "songs"],

    },

    // ============================================================================
    // Instagram Tools
    // ============================================================================
    {
        id: "instagram-caption-generator",
        name: "Instagram Caption Generator",
        nameKey: "instagramCaptionGenerator.title",
        description: "Generate engaging Instagram captions",
        descriptionKey: "instagramCaptionGenerator.description",
        platform: "instagram",
        href: "/instagram/caption-generator",
        icon: "📸",
        dateAdded: "2024-01-01",
        popularity: 88,
        featured: true,
        language: "en",
        tags: ["instagram", "caption", "generator", "engaging"],

    },
    {
        id: "instagram-bio-generator",
        name: "Instagram Bio Generator",
        nameKey: "instagramBioGenerator.title",
        description: "Create a perfect Instagram bio",
        descriptionKey: "instagramBioGenerator.description",
        platform: "instagram",
        href: "/instagram/bio-generator",
        icon: "📸",
        dateAdded: "2024-01-01",
        popularity: 94,
        featured: true,
        language: "en",
        tags: ["instagram", "bio", "generator", "perfect"],

    },
    {
        id: "instagram-hashtag-generator",
        name: "Instagram Hashtag Generator",
        nameKey: "instagramHashtagGenerator.title",
        description: "Find the best hashtags for Instagram",
        descriptionKey: "instagramHashtagGenerator.description",
        platform: "instagram",
        href: "/instagram/hashtag-generator",
        icon: "📸",
        dateAdded: "2024-01-01",
        popularity: 89,
        featured: false,
        language: "en",
        tags: ["instagram", "hashtag", "generator", "best", "hashtags"],

    },
    {
        id: "instagram-reel-script",
        name: "Instagram Reel Script",
        nameKey: "instagramReelScript.title",
        description: "Write scripts for Instagram Reels",
        descriptionKey: "instagramReelScript.description",
        platform: "instagram",
        href: "/instagram/reel-script",
        icon: "📸",
        dateAdded: "2024-01-01",
        popularity: 85,
        featured: true,
        language: "en",
        tags: ["instagram", "reel", "script", "write", "scripts"],

    },
    {
        id: "instagram-story-ideas",
        name: "Instagram Story Ideas",
        nameKey: "instagramStoryIdeas.title",
        description: "Get creative story ideas",
        descriptionKey: "instagramStoryIdeas.description",
        platform: "instagram",
        href: "/instagram/story-ideas",
        icon: "📸",
        dateAdded: "2024-01-01",
        popularity: 91,
        featured: false,
        language: "en",
        tags: ["instagram", "story", "ideas", "creative"],

    },
    {
        id: "instagram-carousel-generator",
        name: "Instagram Carousel Generator",
        nameKey: "instagramCarouselGenerator.title",
        description: "Generate carousel post ideas",
        descriptionKey: "instagramCarouselGenerator.description",
        platform: "instagram",
        href: "/instagram/carousel-generator",
        icon: "📸",
        dateAdded: "2024-01-01",
        popularity: 87,
        featured: false,
        language: "en",
        tags: ["instagram", "carousel", "generator", "post"],

    },
    {
        id: "instagram-engagement-calculator",
        name: "Instagram Engagement Calculator",
        nameKey: "instagramEngagementCalculator.title",
        description: "Calculate your engagement rate",
        descriptionKey: "instagramEngagementCalculator.description",
        platform: "instagram",
        href: "/instagram/engagement-calculator",
        icon: "📸",
        dateAdded: "2024-01-01",
        popularity: 92,
        featured: false,
        language: "en",
        tags: ["instagram", "engagement", "calculator", "calculate"],

    },
    {
        id: "instagram-content-calendar",
        name: "Instagram Content Calendar",
        nameKey: "instagramContentCalendar.title",
        description: "Plan your Instagram content",
        descriptionKey: "instagramContentCalendar.description",
        platform: "instagram",
        href: "/instagram/content-calendar",
        icon: "📸",
        dateAdded: "2024-01-01",
        popularity: 89,
        featured: false,
        language: "en",
        tags: ["instagram", "content", "calendar", "plan"],

    },
    {
        id: "instagram-ad-copy-generator",
        name: "Instagram Ad Copy Generator",
        nameKey: "instagramAdCopyGenerator.title",
        description: "Generate ad copy for Instagram",
        descriptionKey: "instagramAdCopyGenerator.description",
        platform: "instagram",
        href: "/instagram/ad-copy-generator",
        icon: "📸",
        dateAdded: "2024-01-01",
        popularity: 87,
        featured: false,
        language: "en",
        tags: ["instagram", "copy", "generator"],

    },

    // ============================================================================
    // Twitter/X Tools
    // ============================================================================
    {
        id: "twitter-tweet-generator",
        name: "Twitter Tweet Generator",
        nameKey: "tweetGenerator.title",
        description: "Generate viral tweets",
        descriptionKey: "tweetGenerator.description",
        platform: "twitter",
        href: "/twitter/tweet-generator",
        icon: "🐦",
        dateAdded: "2024-01-01",
        popularity: 86,
        featured: true,
        language: "en",
        tags: ["twitter", "tweet", "generator", "viral", "tweets"],

    },
    {
        id: "twitter-thread-maker",
        name: "Twitter Thread Maker",
        nameKey: "threadMaker.title",
        description: "Create engaging Twitter threads",
        descriptionKey: "threadMaker.description",
        platform: "twitter",
        href: "/twitter/thread-maker",
        icon: "🐦",
        dateAdded: "2024-01-01",
        popularity: 81,
        featured: true,
        language: "en",
        tags: ["twitter", "thread", "maker", "engaging"],

    },
    {
        id: "twitter-bio-generator",
        name: "Twitter Bio Generator",
        nameKey: "twitterBioGenerator.title",
        description: "Write the perfect Twitter bio",
        descriptionKey: "twitterBioGenerator.description",
        platform: "twitter",
        href: "/twitter/bio-generator",
        icon: "🐦",
        dateAdded: "2024-01-01",
        popularity: 85,
        featured: true,
        language: "en",
        tags: ["twitter", "bio", "generator", "write", "perfect"],

    },

    // ============================================================================
    // YouTube Tools
    // ============================================================================
    {
        id: "youtube-title-generator",
        name: "YouTube Title Generator",
        nameKey: "youtubeTitleGenerator.title",
        description: "Generate clickable YouTube titles",
        descriptionKey: "youtubeTitleGenerator.description",
        platform: "youtube",
        href: "/youtube/title-generator",
        icon: "📺",
        dateAdded: "2024-01-01",
        popularity: 86,
        featured: true,
        language: "en",
        tags: ["youtube", "title", "generator", "clickable"],

    },
    {
        id: "youtube-description-generator",
        name: "YouTube Description Generator",
        nameKey: "youtubeDescriptionGenerator.title",
        description: "Write SEO-optimized descriptions",
        descriptionKey: "youtubeDescriptionGenerator.description",
        platform: "youtube",
        href: "/youtube/description-generator",
        icon: "📺",
        dateAdded: "2024-01-01",
        popularity: 83,
        featured: true,
        language: "en",
        tags: ["youtube", "description", "generator", "write", "seo"],

    },
    {
        id: "youtube-script-generator",
        name: "YouTube Script Generator",
        nameKey: "youtubeScriptGenerator.title",
        description: "Generate scripts for YouTube videos",
        descriptionKey: "youtubeScriptGenerator.description",
        platform: "youtube",
        href: "/youtube/script-generator",
        icon: "📺",
        dateAdded: "2024-01-01",
        popularity: 84,
        featured: true,
        language: "en",
        tags: ["youtube", "script", "generator", "scripts"],

    },
    {
        id: "youtube-video-ideas",
        name: "YouTube Video Ideas",
        nameKey: "youtubeVideoIdeas.title",
        description: "Get creative video ideas",
        descriptionKey: "youtubeVideoIdeas.description",
        platform: "youtube",
        href: "/youtube/video-ideas",
        icon: "📺",
        dateAdded: "2024-01-01",
        popularity: 86,
        featured: false,
        language: "en",
        tags: ["youtube", "video", "ideas", "creative"],

    },
    {
        id: "youtube-tag-generator",
        name: "YouTube Tag Generator",
        nameKey: "youtubeTagGenerator.title",
        description: "Generate tags for better SEO",
        descriptionKey: "youtubeTagGenerator.description",
        platform: "youtube",
        href: "/youtube/tag-generator",
        icon: "📺",
        dateAdded: "2024-01-01",
        popularity: 90,
        featured: false,
        language: "en",
        tags: ["youtube", "tag", "generator", "tags", "better"],

    },
    {
        id: "youtube-channel-name-generator",
        name: "YouTube Channel Name Generator",
        nameKey: "youtubeChannelNameGenerator.title",
        description: "Find the perfect channel name",
        descriptionKey: "youtubeChannelNameGenerator.description",
        platform: "youtube",
        href: "/youtube/channel-name-generator",
        icon: "📺",
        dateAdded: "2024-01-01",
        popularity: 89,
        featured: false,
        language: "en",
        tags: ["youtube", "channel", "name", "generator", "perfect"],

    },
    {
        id: "youtube-community-post-generator",
        name: "YouTube Community Post Generator",
        nameKey: "youtubeCommunityPostGenerator.title",
        description: "Create community posts",
        descriptionKey: "youtubeCommunityPostGenerator.description",
        platform: "youtube",
        href: "/youtube/community-post-generator",
        icon: "📺",
        dateAdded: "2024-01-01",
        popularity: 84,
        featured: false,
        language: "en",
        tags: ["youtube", "community", "post", "generator"],

    },

    // ============================================================================
    // Reddit Tools
    // ============================================================================
    {
        id: "reddit-post-generator",
        name: "Reddit Post Generator",
        nameKey: "redditPostGenerator.title",
        description: "Generate Reddit posts",
        descriptionKey: "redditPostGenerator.description",
        platform: "reddit",
        href: "/reddit/post-generator",
        icon: "🤖",
        dateAdded: "2024-01-01",
        popularity: 77,
        featured: true,
        language: "en",
        tags: ["reddit", "post", "generator", "posts"],

    },
    {
        id: "reddit-comment-generator",
        name: "Reddit Comment Generator",
        nameKey: "redditCommentGenerator.title",
        description: "Write Reddit comments",
        descriptionKey: "redditCommentGenerator.description",
        platform: "reddit",
        href: "/reddit/comment-generator",
        icon: "🤖",
        dateAdded: "2024-01-01",
        popularity: 80,
        featured: false,
        language: "en",
        tags: ["reddit", "comment", "generator", "write"],

    },
    {
        id: "reddit-ama-questions",
        name: "Reddit AMA Questions",
        nameKey: "redditAmaQuestions.title",
        description: "Generate AMA questions",
        descriptionKey: "redditAmaQuestions.description",
        platform: "reddit",
        href: "/reddit/ama-questions",
        icon: "🤖",
        dateAdded: "2024-01-01",
        popularity: 76,
        featured: false,
        language: "en",
        tags: ["reddit", "ama", "questions"],

    },

    // ============================================================================
    // Discord Tools
    // ============================================================================
    {
        id: "discord-announcement-generator",
        name: "Discord Announcement Generator",
        nameKey: "discordAnnouncementGenerator.title",
        description: "Create server announcements",
        descriptionKey: "discordAnnouncementGenerator.description",
        platform: "discord",
        href: "/discord/announcement-generator",
        icon: "💬",
        dateAdded: "2024-01-01",
        popularity: 74,
        featured: true,
        language: "en",
        tags: ["discord", "announcement", "generator", "server", "announcements"],

    },
    {
        id: "discord-welcome-message",
        name: "Discord Welcome Message",
        nameKey: "discordWelcomeMessage.title",
        description: "Write welcome messages",
        descriptionKey: "discordWelcomeMessage.description",
        platform: "discord",
        href: "/discord/welcome-message",
        icon: "💬",
        dateAdded: "2024-01-01",
        popularity: 70,
        featured: false,
        language: "en",
        tags: ["discord", "welcome", "message", "write"],

    },
    {
        id: "discord-event-description",
        name: "Discord Event Description",
        nameKey: "discordEventDescription.title",
        description: "Create event descriptions",
        descriptionKey: "discordEventDescription.description",
        platform: "discord",
        href: "/discord/event-description",
        icon: "💬",
        dateAdded: "2024-01-01",
        popularity: 69,
        featured: false,
        language: "en",
        tags: ["discord", "event", "description", "descriptions"],

    },

    // ============================================================================
    // Snapchat Tools
    // ============================================================================
    {
        id: "snapchat-caption-generator",
        name: "Snapchat Caption Generator",
        nameKey: "snapchatCaptionGenerator.title",
        description: "Generate Snapchat captions",
        descriptionKey: "snapchatCaptionGenerator.description",
        platform: "snapchat",
        href: "/snapchat/caption-generator",
        icon: "👻",
        dateAdded: "2024-01-01",
        popularity: 77,
        featured: true,
        language: "en",
        tags: ["snapchat", "caption", "generator", "captions"],

    },
    {
        id: "snapchat-story-ideas",
        name: "Snapchat Story Ideas",
        nameKey: "snapchatStoryIdeas.title",
        description: "Get story ideas",
        descriptionKey: "snapchatStoryIdeas.description",
        platform: "snapchat",
        href: "/snapchat/story-ideas",
        icon: "👻",
        dateAdded: "2024-01-01",
        popularity: 83,
        featured: true,
        language: "en",
        tags: ["snapchat", "story", "ideas"],

    },
    {
        id: "snapchat-lens-ideas",
        name: "Snapchat Lens Ideas",
        nameKey: "snapchatLensIdeas.title",
        description: "Creative lens ideas",
        descriptionKey: "snapchatLensIdeas.description",
        platform: "snapchat",
        href: "/snapchat/lens-ideas",
        icon: "👻",
        dateAdded: "2024-01-01",
        popularity: 83,
        featured: false,
        language: "en",
        tags: ["snapchat", "lens", "ideas", "creative"],

    },

    // ============================================================================
    // Suno Tools
    // ============================================================================
    {
        id: "suno-lyric-generator",
        name: "Suno Lyric Generator",
        nameKey: "sunoLyricGenerator.title",
        description: "Generate song lyrics",
        descriptionKey: "sunoLyricGenerator.description",
        platform: "suno",
        href: "/suno/lyric-generator",
        icon: "🎵",
        dateAdded: "2024-01-01",
        popularity: 69,
        featured: true,
        language: "en",
        tags: ["suno", "lyric", "generator", "song", "lyrics"],

    },
    {
        id: "suno-music-prompt-generator",
        name: "Suno Music Prompt Generator",
        nameKey: "sunoMusicPromptGenerator.title",
        description: "Create music prompts",
        descriptionKey: "sunoMusicPromptGenerator.description",
        platform: "suno",
        href: "/suno/music-prompt-generator",
        icon: "🎵",
        dateAdded: "2024-01-01",
        popularity: 60,
        featured: false,
        language: "en",
        tags: ["suno", "music", "prompt", "generator"],

    },
    {
        id: "suno-song-title-generator",
        name: "Suno Song Title Generator",
        nameKey: "sunoSongTitleGenerator.title",
        description: "Generate song titles",
        descriptionKey: "sunoSongTitleGenerator.description",
        platform: "suno",
        href: "/suno/song-title-generator",
        icon: "🎵",
        dateAdded: "2024-01-01",
        popularity: 67,
        featured: false,
        language: "en",
        tags: ["suno", "song", "title", "generator"],

    },
    {
        id: "suno-song-description-generator",
        name: "Suno Song Description Generator",
        nameKey: "sunoSongDescriptionGenerator.title",
        description: "Write song descriptions",
        descriptionKey: "sunoSongDescriptionGenerator.description",
        platform: "suno",
        href: "/suno/song-description-generator",
        icon: "🎵",
        dateAdded: "2024-01-01",
        popularity: 64,
        featured: false,
        language: "en",
        tags: ["suno", "song", "description", "generator", "write"],

    },
    {
        id: "suno-album-name-generator",
        name: "Suno Album Name Generator",
        nameKey: "sunoAlbumNameGenerator.title",
        description: "Generate album names",
        descriptionKey: "sunoAlbumNameGenerator.description",
        platform: "suno",
        href: "/suno/album-name-generator",
        icon: "🎵",
        dateAdded: "2024-01-01",
        popularity: 61,
        featured: false,
        language: "en",
        tags: ["suno", "album", "name", "generator"],

    },
    {
        id: "suno-cover-art-prompt-generator",
        name: "Suno Cover Art Prompt Generator",
        nameKey: "sunoCoverArtPromptGenerator.title",
        description: "Create cover art prompts",
        descriptionKey: "sunoCoverArtPromptGenerator.description",
        platform: "suno",
        href: "/suno/cover-art-prompt-generator",
        icon: "🎵",
        dateAdded: "2024-01-01",
        popularity: 66,
        featured: false,
        language: "en",
        tags: ["suno", "cover", "art", "prompt", "generator"],

    },
    {
        id: "suno-remix-idea-generator",
        name: "Suno Remix Idea Generator",
        nameKey: "sunoRemixIdeaGenerator.title",
        description: "Get remix ideas",
        descriptionKey: "sunoRemixIdeaGenerator.description",
        platform: "suno",
        href: "/suno/remix-idea-generator",
        icon: "🎵",
        dateAdded: "2024-01-01",
        popularity: 68,
        featured: false,
        language: "en",
        tags: ["suno", "remix", "idea", "generator"],

    },
    {
        id: "suno-song-tag-generator",
        name: "Suno Song Tag Generator",
        nameKey: "sunoSongTagGenerator.title",
        description: "Generate song tags",
        descriptionKey: "sunoSongTagGenerator.description",
        platform: "suno",
        href: "/suno/song-tag-generator",
        icon: "🎵",
        dateAdded: "2024-01-01",
        popularity: 60,
        featured: false,
        language: "en",
        tags: ["suno", "song", "tag", "generator"],

    },

    // ============================================================================
    // ElevenLabs Tools
    // ============================================================================
    {
        id: "elevenlabs-voice-script-writer",
        name: "ElevenLabs Voice Script Writer",
        nameKey: "voiceScriptWriter.title",
        description: "Write voice scripts with pauses",
        descriptionKey: "voiceScriptWriter.description",
        platform: "elevenlabs",
        href: "/elevenlabs/voice-script-writer",
        icon: "🎙️",
        dateAdded: "2024-01-01",
        popularity: 61,
        featured: true,
        language: "en",
        tags: ["elevenlabs", "voice", "script", "writer", "write"],

    },
    {
        id: "elevenlabs-video-voiceover-script",
        name: "ElevenLabs Video Voiceover Script",
        nameKey: "videoVoiceoverScript.title",
        description: "Create video voiceover scripts",
        descriptionKey: "videoVoiceoverScript.description",
        platform: "elevenlabs",
        href: "/elevenlabs/video-voiceover-script",
        icon: "🎙️",
        dateAdded: "2024-01-01",
        popularity: 69,
        featured: false,
        language: "en",
        tags: ["elevenlabs", "video", "voiceover", "script"],

    },
    {
        id: "elevenlabs-podcast-script",
        name: "ElevenLabs Podcast Script",
        nameKey: "podcastScript.title",
        description: "Write podcast scripts",
        descriptionKey: "podcastScript.description",
        platform: "elevenlabs",
        href: "/elevenlabs/podcast-script",
        icon: "🎙️",
        dateAdded: "2024-01-01",
        popularity: 61,
        featured: false,
        language: "en",
        tags: ["elevenlabs", "podcast", "script", "write"],

    },
    {
        id: "elevenlabs-ad-script",
        name: "ElevenLabs Ad Script",
        nameKey: "adScript.title",
        description: "Generate ad scripts",
        descriptionKey: "adScript.description",
        platform: "elevenlabs",
        href: "/elevenlabs/ad-script",
        icon: "🎙️",
        dateAdded: "2024-01-01",
        popularity: 70,
        featured: false,
        language: "en",
        tags: ["elevenlabs", "script", "scripts"],

    },
    {
        id: "elevenlabs-audiobook-optimizer",
        name: "ElevenLabs Audiobook Optimizer",
        nameKey: "audiobookOptimizer.title",
        description: "Optimize audiobook scripts",
        descriptionKey: "audiobookOptimizer.description",
        platform: "elevenlabs",
        href: "/elevenlabs/audiobook-optimizer",
        icon: "🎙️",
        dateAdded: "2024-01-01",
        popularity: 67,
        featured: false,
        language: "en",
        tags: ["elevenlabs", "audiobook", "optimizer", "optimize"],

    },
    {
        id: "elevenlabs-voice-text-formatter",
        name: "ElevenLabs Voice Text Formatter",
        nameKey: "voiceTextFormatter.title",
        description: "Format text for voice",
        descriptionKey: "voiceTextFormatter.description",
        platform: "elevenlabs",
        href: "/elevenlabs/voice-text-formatter",
        icon: "🎙️",
        dateAdded: "2024-01-01",
        popularity: 61,
        featured: false,
        language: "en",
        tags: ["elevenlabs", "voice", "text", "formatter", "format"],

    },

    // ============================================================================
    // LinkedIn Tools
    // ============================================================================
    {
        id: "linkedin-post-generator",
        name: "LinkedIn Post Generator",
        nameKey: "linkedinPostGenerator.title",
        description: "Generate LinkedIn posts",
        descriptionKey: "linkedinPostGenerator.description",
        platform: "linkedin",
        href: "/linkedin/post-generator",
        icon: "💼",
        dateAdded: "2024-01-01",
        popularity: 78,
        featured: false,
        language: "en",
        tags: ["linkedin", "post", "generator", "posts"],

    },
    {
        id: "linkedin-headline-generator",
        name: "LinkedIn Headline Generator",
        nameKey: "linkedinHeadlineGenerator.title",
        description: "Create compelling headlines",
        descriptionKey: "linkedinHeadlineGenerator.description",
        platform: "linkedin",
        href: "/linkedin/headline-generator",
        icon: "💼",
        dateAdded: "2024-01-01",
        popularity: 78,
        featured: false,
        language: "en",
        tags: ["linkedin", "headline", "generator", "compelling", "headlines"],

    },
    {
        id: "linkedin-about-generator",
        name: "LinkedIn About Generator",
        nameKey: "linkedinAboutGenerator.title",
        description: "Write your About section",
        descriptionKey: "linkedinAboutGenerator.description",
        platform: "linkedin",
        href: "/linkedin/about-generator",
        icon: "💼",
        dateAdded: "2024-01-01",
        popularity: 71,
        featured: false,
        language: "en",
        tags: ["linkedin", "about", "generator", "write"],

    },

    // ============================================================================
    // Twitch Tools
    // ============================================================================
    {
        id: "twitch-bio-generator",
        name: "Twitch Bio Generator",
        nameKey: "twitchBioGenerator.title",
        description: "Create your Twitch bio",
        descriptionKey: "twitchBioGenerator.description",
        platform: "twitch",
        href: "/twitch/bio-generator",
        icon: "🎮",
        dateAdded: "2024-01-01",
        popularity: 75,
        featured: false,
        language: "en",
        tags: ["twitch", "bio", "generator"],

    },
    {
        id: "twitch-stream-title",
        name: "Twitch Stream Title Generator",
        nameKey: "twitchStreamTitle.title",
        description: "Generate stream titles",
        descriptionKey: "twitchStreamTitle.description",
        platform: "twitch",
        href: "/twitch/stream-title",
        icon: "🎮",
        dateAdded: "2024-01-01",
        popularity: 66,
        featured: false,
        language: "en",
        tags: ["twitch", "stream", "title", "generator"],

    },
    {
        id: "twitch-panel-description",
        name: "Twitch Panel Description",
        nameKey: "twitchPanelDescription.title",
        description: "Write panel descriptions",
        descriptionKey: "twitchPanelDescription.description",
        platform: "twitch",
        href: "/twitch/panel-description",
        icon: "🎮",
        dateAdded: "2024-01-01",
        popularity: 68,
        featured: false,
        language: "en",
        tags: ["twitch", "panel", "description", "write"],

    },
    {
        id: "twitch-chat-command",
        name: "Twitch Chat Command Generator",
        nameKey: "twitchChatCommand.title",
        description: "Create chat commands",
        descriptionKey: "twitchChatCommand.description",
        platform: "twitch",
        href: "/twitch/chat-command",
        icon: "🎮",
        dateAdded: "2024-01-01",
        popularity: 71,
        featured: false,
        language: "en",
        tags: ["twitch", "chat", "command", "generator"],

    },
    {
        id: "twitch-rules-generator",
        name: "Twitch Rules Generator",
        nameKey: "twitchRulesGenerator.title",
        description: "Generate channel rules",
        descriptionKey: "twitchRulesGenerator.description",
        platform: "twitch",
        href: "/twitch/rules-generator",
        icon: "🎮",
        dateAdded: "2024-01-01",
        popularity: 75,
        featured: false,
        language: "en",
        tags: ["twitch", "rules", "generator", "channel"],

    },
    {
        id: "twitch-stream-plan-generator",
        name: "Twitch Stream Plan Generator",
        nameKey: "twitchStreamPlanGenerator.title",
        description: "Plan your streams",
        descriptionKey: "twitchStreamPlanGenerator.description",
        platform: "twitch",
        href: "/twitch/stream-plan-generator",
        icon: "🎮",
        dateAdded: "2024-01-01",
        popularity: 65,
        featured: false,
        language: "en",
        tags: ["twitch", "stream", "plan", "generator"],

    },

    // ============================================================================
    // Kick Tools
    // ============================================================================
    {
        id: "kick-bio-generator",
        name: "Kick Bio Generator",
        nameKey: "kickBioGenerator.title",
        description: "Create your Kick bio",
        descriptionKey: "kickBioGenerator.description",
        platform: "kick",
        href: "/kick/bio-generator",
        icon: "🥊",
        dateAdded: "2024-01-01",
        popularity: 62,
        featured: false,
        language: "en",
        tags: ["kick", "bio", "generator"],

    },
    {
        id: "kick-stream-title",
        name: "Kick Stream Title Generator",
        nameKey: "kickStreamTitle.title",
        description: "Generate stream titles",
        descriptionKey: "kickStreamTitle.description",
        platform: "kick",
        href: "/kick/stream-title",
        icon: "🥊",
        dateAdded: "2024-01-01",
        popularity: 62,
        featured: false,
        language: "en",
        tags: ["kick", "stream", "title", "generator"],

    },
    {
        id: "kick-chat-rules",
        name: "Kick Chat Rules Generator",
        nameKey: "kickChatRules.title",
        description: "Create chat rules",
        descriptionKey: "kickChatRules.description",
        platform: "kick",
        href: "/kick/chat-rules",
        icon: "🥊",
        dateAdded: "2024-01-01",
        popularity: 59,
        featured: false,
        language: "en",
        tags: ["kick", "chat", "rules", "generator"],

    },

    // ============================================================================
    // Spotify Tools
    // ============================================================================
    {
        id: "spotify-playlist-name",
        name: "Spotify Playlist Name Generator",
        nameKey: "spotifyPlaylistName.title",
        description: "Generate playlist names",
        descriptionKey: "spotifyPlaylistName.description",
        platform: "spotify",
        href: "/spotify/playlist-name",
        icon: "🎧",
        dateAdded: "2024-01-01",
        popularity: 59,
        featured: false,
        language: "en",
        tags: ["spotify", "playlist", "name", "generator"],

    },
    {
        id: "spotify-playlist-description",
        name: "Spotify Playlist Description",
        nameKey: "spotifyPlaylistDescription.title",
        description: "Write playlist descriptions",
        descriptionKey: "spotifyPlaylistDescription.description",
        platform: "spotify",
        href: "/spotify/playlist-description",
        icon: "🎧",
        dateAdded: "2024-01-01",
        popularity: 56,
        featured: false,
        language: "en",
        tags: ["spotify", "playlist", "description", "write"],

    },
    {
        id: "spotify-artist-bio",
        name: "Spotify Artist Bio Generator",
        nameKey: "spotifyArtistBio.title",
        description: "Create your artist bio",
        descriptionKey: "spotifyArtistBio.description",
        platform: "spotify",
        href: "/spotify/artist-bio",
        icon: "🎧",
        dateAdded: "2024-01-01",
        popularity: 57,
        featured: false,
        language: "en",
        tags: ["spotify", "artist", "bio", "generator"],

    },

    // ============================================================================
    // Facebook Tools
    // ============================================================================
    {
        id: "facebook-post-generator",
        name: "Facebook Post Generator",
        nameKey: "facebookPostGenerator.title",
        description: "Generate Facebook posts",
        descriptionKey: "facebookPostGenerator.description",
        platform: "facebook",
        href: "/facebook/post-generator",
        icon: "👍",
        dateAdded: "2024-01-01",
        popularity: 78,
        featured: false,
        language: "en",
        tags: ["facebook", "post", "generator", "posts"],

    },
    {
        id: "facebook-ad-copy",
        name: "Facebook Ad Copy Generator",
        nameKey: "facebookAdCopy.title",
        description: "Create ad copy for Facebook",
        descriptionKey: "facebookAdCopy.description",
        platform: "facebook",
        href: "/facebook/ad-copy",
        icon: "👍",
        dateAdded: "2024-01-01",
        popularity: 74,
        featured: false,
        language: "en",
        tags: ["facebook", "copy", "generator"],

    },
    {
        id: "facebook-page-bio",
        name: "Facebook Page Bio Generator",
        nameKey: "facebookPageBio.title",
        description: "Write your page bio",
        descriptionKey: "facebookPageBio.description",
        platform: "facebook",
        href: "/facebook/page-bio",
        icon: "👍",
        dateAdded: "2024-01-01",
        popularity: 80,
        featured: false,
        language: "en",
        tags: ["facebook", "page", "bio", "generator", "write"],

    },

    // ============================================================================
    // Pinterest Tools
    // ============================================================================
    {
        id: "pinterest-pin-description",
        name: "Pinterest Pin Description",
        nameKey: "pinterestPinDescription.title",
        description: "Write pin descriptions",
        descriptionKey: "pinterestPinDescription.description",
        platform: "pinterest",
        href: "/pinterest/pin-description",
        icon: "📌",
        dateAdded: "2024-01-01",
        popularity: 54,
        featured: false,
        language: "en",
        tags: ["pinterest", "pin", "description", "write"],

    },
    {
        id: "pinterest-board-name",
        name: "Pinterest Board Name Generator",
        nameKey: "pinterestBoardName.title",
        description: "Generate board names",
        descriptionKey: "pinterestBoardName.description",
        platform: "pinterest",
        href: "/pinterest/board-name",
        icon: "📌",
        dateAdded: "2024-01-01",
        popularity: 52,
        featured: false,
        language: "en",
        tags: ["pinterest", "board", "name", "generator"],

    },
    {
        id: "pinterest-profile-bio",
        name: "Pinterest Profile Bio",
        nameKey: "pinterestProfileBio.title",
        description: "Create your profile bio",
        descriptionKey: "pinterestProfileBio.description",
        platform: "pinterest",
        href: "/pinterest/profile-bio",
        icon: "📌",
        dateAdded: "2024-01-01",
        popularity: 59,
        featured: false,
        language: "en",
        tags: ["pinterest", "profile", "bio"],

    },

    // ============================================================================
    // Bluesky Tools
    // ============================================================================
    {
        id: "bluesky-post-generator",
        name: "Bluesky Post Generator",
        nameKey: "blueskyPostGenerator.title",
        description: "Generate Bluesky posts",
        descriptionKey: "blueskyPostGenerator.description",
        platform: "bluesky",
        href: "/bluesky/post-generator",
        icon: "🦋",
        dateAdded: "2024-01-01",
        popularity: 63,
        featured: false,
        language: "en",
        tags: ["bluesky", "post", "generator", "posts"],

    },
    {
        id: "bluesky-bio-generator",
        name: "Bluesky Bio Generator",
        nameKey: "blueskyBioGenerator.title",
        description: "Create your Bluesky bio",
        descriptionKey: "blueskyBioGenerator.description",
        platform: "bluesky",
        href: "/bluesky/bio-generator",
        icon: "🦋",
        dateAdded: "2024-01-01",
        popularity: 50,
        featured: false,
        language: "en",
        tags: ["bluesky", "bio", "generator"],

    },
    {
        id: "bluesky-thread-composer",
        name: "Bluesky Thread Composer",
        nameKey: "blueskyThreadComposer.title",
        description: "Compose Bluesky threads",
        descriptionKey: "blueskyThreadComposer.description",
        platform: "bluesky",
        href: "/bluesky/thread-composer",
        icon: "🦋",
        dateAdded: "2024-01-01",
        popularity: 50,
        featured: false,
        language: "en",
        tags: ["bluesky", "thread", "composer", "compose"],

    },

    // ============================================================================
    // Telegram Tools
    // ============================================================================
    {
        id: "telegram-channel-description",
        name: "Telegram Channel Description",
        nameKey: "telegramChannelDescription.title",
        description: "Write channel descriptions",
        descriptionKey: "telegramChannelDescription.description",
        platform: "telegram",
        href: "/telegram/channel-description",
        icon: "✈️",
        dateAdded: "2024-01-01",
        popularity: 52,
        featured: false,
        language: "en",
        tags: ["telegram", "channel", "description", "write"],

    },
    {
        id: "telegram-welcome-message",
        name: "Telegram Welcome Message",
        nameKey: "telegramWelcomeMessage.title",
        description: "Create welcome messages",
        descriptionKey: "telegramWelcomeMessage.description",
        platform: "telegram",
        href: "/telegram/welcome-message",
        icon: "✈️",
        dateAdded: "2024-01-01",
        popularity: 61,
        featured: false,
        language: "en",
        tags: ["telegram", "welcome", "message", "messages"],

    },
    {
        id: "telegram-announcement-generator",
        name: "Telegram Announcement Generator",
        nameKey: "telegramAnnouncementGenerator.title",
        description: "Generate announcements",
        descriptionKey: "telegramAnnouncementGenerator.description",
        platform: "telegram",
        href: "/telegram/announcement-generator",
        icon: "✈️",
        dateAdded: "2024-01-01",
        popularity: 51,
        featured: false,
        language: "en",
        tags: ["telegram", "announcement", "generator", "announcements"],

    },

    // ============================================================================
    // BeReal Tools
    // ============================================================================
    {
        id: "bereal-caption-generator",
        name: "BeReal Caption Generator",
        nameKey: "berealCaptionGenerator.title",
        description: "Generate BeReal captions",
        descriptionKey: "berealCaptionGenerator.description",
        platform: "bereal",
        href: "/bereal/caption-generator",
        icon: "📷",
        dateAdded: "2024-01-01",
        popularity: 58,
        featured: false,
        language: "en",
        tags: ["bereal", "caption", "generator", "captions"],

    },
    {
        id: "bereal-bio-generator",
        name: "BeReal Bio Generator",
        nameKey: "berealBioGenerator.title",
        description: "Create your BeReal bio",
        descriptionKey: "berealBioGenerator.description",
        platform: "bereal",
        href: "/bereal/bio-generator",
        icon: "📷",
        dateAdded: "2024-01-01",
        popularity: 56,
        featured: false,
        language: "en",
        tags: ["bereal", "bio", "generator"],

    },
    {
        id: "bereal-realmoji-ideas",
        name: "BeReal RealMoji Ideas",
        nameKey: "berealRealmojiIdeas.title",
        description: "Get RealMoji ideas",
        descriptionKey: "berealRealmojiIdeas.description",
        platform: "bereal",
        href: "/bereal/realmoji-ideas",
        icon: "📷",
        dateAdded: "2024-01-01",
        popularity: 63,
        featured: false,
        language: "en",
        tags: ["bereal", "realmoji", "ideas"],

    },

    // ============================================================================
    // Medium Tools
    // ============================================================================
    {
        id: "medium-article-title-generator",
        name: "Medium Article Title Generator",
        nameKey: "mediumArticleTitleGenerator.title",
        description: "Generate article titles",
        descriptionKey: "mediumArticleTitleGenerator.description",
        platform: "medium",
        href: "/medium/article-title-generator",
        icon: "📝",
        dateAdded: "2024-01-01",
        popularity: 50,
        featured: false,
        language: "en",
        tags: ["medium", "article", "title", "generator"],

    },
    {
        id: "medium-article-intro-generator",
        name: "Medium Article Intro Generator",
        nameKey: "mediumArticleIntroGenerator.title",
        description: "Write article intros",
        descriptionKey: "mediumArticleIntroGenerator.description",
        platform: "medium",
        href: "/medium/article-intro-generator",
        icon: "📝",
        dateAdded: "2024-01-01",
        popularity: 61,
        featured: false,
        language: "en",
        tags: ["medium", "article", "intro", "generator", "write"],

    },
    {
        id: "medium-bio-generator",
        name: "Medium Bio Generator",
        nameKey: "mediumBioGenerator.title",
        description: "Create your Medium bio",
        descriptionKey: "mediumBioGenerator.description",
        platform: "medium",
        href: "/medium/bio-generator",
        icon: "📝",
        dateAdded: "2024-01-01",
        popularity: 64,
        featured: false,
        language: "en",
        tags: ["medium", "bio", "generator"],

    },

    // ============================================================================
    // Etsy Tools
    // ============================================================================
    {
        id: "etsy-product-title-generator",
        name: "Etsy Product Title Generator",
        nameKey: "etsyProductTitleGenerator.title",
        description: "Generate product titles",
        descriptionKey: "etsyProductTitleGenerator.description",
        platform: "etsy",
        href: "/etsy/product-title-generator",
        icon: "🛒",
        dateAdded: "2024-01-01",
        popularity: 62,
        featured: false,
        language: "en",
        tags: ["etsy", "product", "title", "generator"],

    },
    {
        id: "etsy-product-description-generator",
        name: "Etsy Product Description Generator",
        nameKey: "etsyProductDescriptionGenerator.title",
        description: "Write product descriptions",
        descriptionKey: "etsyProductDescriptionGenerator.description",
        platform: "etsy",
        href: "/etsy/product-description-generator",
        icon: "🛒",
        dateAdded: "2024-01-01",
        popularity: 55,
        featured: false,
        language: "en",
        tags: ["etsy", "product", "description", "generator", "write"],

    },
    {
        id: "etsy-shop-announcement-generator",
        name: "Etsy Shop Announcement Generator",
        nameKey: "etsyShopAnnouncementGenerator.title",
        description: "Create shop announcements",
        descriptionKey: "etsyShopAnnouncementGenerator.description",
        platform: "etsy",
        href: "/etsy/shop-announcement-generator",
        icon: "🛒",
        dateAdded: "2024-01-01",
        popularity: 54,
        featured: false,
        language: "en",
        tags: ["etsy", "shop", "announcement", "generator"],

    },

    // ============================================================================
    // OnlyFans Tools
    // ============================================================================
    {
        id: "onlyfans-bio-generator",
        name: "OnlyFans Bio Generator",
        nameKey: "onlyfansBioGenerator.title",
        description: "Create your OnlyFans bio",
        descriptionKey: "onlyfansBioGenerator.description",
        platform: "onlyfans",
        href: "/onlyfans/bio-generator",
        icon: "💎",
        dateAdded: "2024-01-01",
        popularity: 50,
        featured: false,
        language: "en",
        tags: ["onlyfans", "bio", "generator"],

    },
    {
        id: "onlyfans-post-caption-generator",
        name: "OnlyFans Post Caption Generator",
        nameKey: "onlyfansPostCaptionGenerator.title",
        description: "Generate post captions",
        descriptionKey: "onlyfansPostCaptionGenerator.description",
        platform: "onlyfans",
        href: "/onlyfans/post-caption-generator",
        icon: "💎",
        dateAdded: "2024-01-01",
        popularity: 63,
        featured: false,
        language: "en",
        tags: ["onlyfans", "post", "caption", "generator"],

    },
    {
        id: "onlyfans-promo-generator",
        name: "OnlyFans Promo Generator",
        nameKey: "onlyfansPromoGenerator.title",
        description: "Create promotional content",
        descriptionKey: "onlyfansPromoGenerator.description",
        platform: "onlyfans",
        href: "/onlyfans/promo-generator",
        icon: "💎",
        dateAdded: "2024-01-01",
        popularity: 52,
        featured: false,
        language: "en",
        tags: ["onlyfans", "promo", "generator", "promotional", "content"],

    },

    // ============================================================================
    // Patreon Tools
    // ============================================================================
    {
        id: "patreon-about-page-generator",
        name: "Patreon About Page Generator",
        nameKey: "patreonAboutPageGenerator.title",
        description: "Write your About page",
        descriptionKey: "patreonAboutPageGenerator.description",
        platform: "patreon",
        href: "/patreon/about-page-generator",
        icon: "🎨",
        dateAdded: "2024-01-01",
        popularity: 62,
        featured: false,
        language: "en",
        tags: ["patreon", "about", "page", "generator", "write"],

    },
    {
        id: "patreon-post-generator",
        name: "Patreon Post Generator",
        nameKey: "patreonPostGenerator.title",
        description: "Generate Patreon posts",
        descriptionKey: "patreonPostGenerator.description",
        platform: "patreon",
        href: "/patreon/post-generator",
        icon: "🎨",
        dateAdded: "2024-01-01",
        popularity: 64,
        featured: false,
        language: "en",
        tags: ["patreon", "post", "generator", "posts"],

    },
    {
        id: "patreon-tier-description-generator",
        name: "Patreon Tier Description Generator",
        nameKey: "patreonTierDescriptionGenerator.title",
        description: "Write tier descriptions",
        descriptionKey: "patreonTierDescriptionGenerator.description",
        platform: "patreon",
        href: "/patreon/tier-description-generator",
        icon: "🎨",
        dateAdded: "2024-01-01",
        popularity: 65,
        featured: false,
        language: "en",
        tags: ["patreon", "tier", "description", "generator", "write"],

    },

    // ============================================================================
    // Dating Tools
    // ============================================================================
    {
        id: "dating-bio-generator",
        name: "Dating Bio Generator",
        nameKey: "datingBioGenerator.title",
        description: "Create your dating profile bio",
        descriptionKey: "datingBioGenerator.description",
        platform: "dating",
        href: "/dating/bio-generator",
        icon: "💕",
        dateAdded: "2024-01-01",
        popularity: 62,
        featured: false,
        language: "en",
        tags: ["dating", "bio", "generator", "profile"],

    },
    {
        id: "dating-opener-generator",
        name: "Dating Opener Generator",
        nameKey: "datingOpenerGenerator.title",
        description: "Generate conversation openers",
        descriptionKey: "datingOpenerGenerator.description",
        platform: "dating",
        href: "/dating/opener-generator",
        icon: "💕",
        dateAdded: "2024-01-01",
        popularity: 65,
        featured: false,
        language: "en",
        tags: ["dating", "opener", "generator", "conversation", "openers"],

    },
    {
        id: "dating-profile-review",
        name: "Dating Profile Review",
        nameKey: "datingProfileReview.title",
        description: "Get profile feedback",
        descriptionKey: "datingProfileReview.description",
        platform: "dating",
        href: "/dating/profile-review",
        icon: "💕",
        dateAdded: "2024-01-01",
        popularity: 52,
        featured: false,
        language: "en",
        tags: ["dating", "profile", "review", "feedback"],

    },

    // ============================================================================
    // Amazon Tools
    // ============================================================================
    {
        id: "amazon-product-description-generator",
        name: "Amazon Product Description Generator",
        nameKey: "amazonProductDescriptionGenerator.title",
        description: "Write product descriptions",
        descriptionKey: "amazonProductDescriptionGenerator.description",
        platform: "amazon",
        href: "/amazon/product-description-generator",
        icon: "📦",
        dateAdded: "2024-01-01",
        popularity: 59,
        featured: false,
        language: "en",
        tags: ["amazon", "product", "description", "generator", "write"],

    },
    {
        id: "amazon-product-review-generator",
        name: "Amazon Product Review Generator",
        nameKey: "amazonProductReviewGenerator.title",
        description: "Generate product reviews",
        descriptionKey: "amazonProductReviewGenerator.description",
        platform: "amazon",
        href: "/amazon/product-review-generator",
        icon: "📦",
        dateAdded: "2024-01-01",
        popularity: 65,
        featured: false,
        language: "en",
        tags: ["amazon", "product", "review", "generator"],

    },
    {
        id: "amazon-product-comparison-generator",
        name: "Amazon Product Comparison Generator",
        nameKey: "amazonProductComparisonGenerator.title",
        description: "Compare products",
        descriptionKey: "amazonProductComparisonGenerator.description",
        platform: "amazon",
        href: "/amazon/product-comparison-generator",
        icon: "📦",
        dateAdded: "2024-01-01",
        popularity: 62,
        featured: false,
        language: "en",
        tags: ["amazon", "product", "comparison", "generator", "compare"],

    },

    // ============================================================================
    // Forocoches Tools
    // ============================================================================
    {
        id: "forocoches-thread-generator",
        name: "Forocoches Thread Generator",
        nameKey: "forocochesThreadGenerator.title",
        description: "Generate forum threads",
        descriptionKey: "forocochesThreadGenerator.description",
        platform: "forocoches",
        href: "/forocoches/thread-generator",
        icon: "🚗",
        dateAdded: "2024-01-01",
        popularity: 51,
        featured: false,
        language: "en",
        tags: ["forocoches", "thread", "generator", "forum", "threads"],

    },
    {
        id: "forocoches-pole-generator",
        name: "Forocoches Pole Generator",
        nameKey: "forocochesPolesGenerator.title",
        description: "Create pole posts",
        descriptionKey: "forocochesPolesGenerator.description",
        platform: "forocoches",
        href: "/forocoches/pole-generator",
        icon: "🚗",
        dateAdded: "2024-01-01",
        popularity: 63,
        featured: false,
        language: "en",
        tags: ["forocoches", "pole", "generator", "posts"],

    },
    {
        id: "forocoches-troll-response",
        name: "Forocoches Troll Response",
        nameKey: "forocochesTorollResponse.title",
        description: "Generate troll responses",
        descriptionKey: "forocochesTorollResponse.description",
        platform: "forocoches",
        href: "/forocoches/troll-response",
        icon: "🚗",
        dateAdded: "2024-01-01",
        popularity: 60,
        featured: false,
        language: "en",
        tags: ["forocoches", "troll", "response", "responses"],

    },

    // ============================================================================
    // Podcast Tools
    // ============================================================================
    {
        id: "podcast-name-generator",
        name: "Podcast Name Generator",
        nameKey: "podcastNameGenerator.title",
        description: "Generate podcast names",
        descriptionKey: "podcastNameGenerator.description",
        platform: "podcast",
        href: "/podcast/name-generator",
        icon: "🎙️",
        dateAdded: "2024-01-01",
        popularity: 64,
        featured: false,
        language: "en",
        tags: ["podcast", "name", "generator", "names"],

    },
];

/**
 * Complete list of all platforms for filtering.
 * Feature: 017-homepage-tools-feed
 */
export const PLATFORMS: Platform[] = [
    "tiktok",
    "instagram",
    "twitter",
    "snapchat",
    "youtube",
    "reddit",
    "discord",
    "twitch",
    "elevenlabs",
    "amazon",
    "bereal",
    "bluesky",
    "dating",
    "email",
    "etsy",
    "facebook",
    "forocoches",
    "kick",
    "linkedin",
    "mastodon",
    "medium",
    "onlyfans",
    "patreon",
    "pinterest",
    "podcast",
    "shopify",
    "suno",
    "telegram",
    "threads",
    "vimeo",
    "whatsapp",
    "wordpress"
] as const;

/**
 * Platform metadata for search result display.
 */
export const PLATFORM_METADATA: Record<
    string,
    { name: string; icon: string; color: string }
> = {
    tiktok: { name: "TikTok", icon: "🎵", color: "purple" },
    instagram: { name: "Instagram", icon: "📸", color: "pink" },
    twitter: { name: "Twitter", icon: "🐦", color: "blue" },
    youtube: { name: "YouTube", icon: "📺", color: "red" },
    reddit: { name: "Reddit", icon: "🤖", color: "orange" },
    discord: { name: "Discord", icon: "💬", color: "indigo" },
    snapchat: { name: "Snapchat", icon: "👻", color: "yellow" },
    suno: { name: "Suno", icon: "🎵", color: "purple" },
    elevenlabs: { name: "ElevenLabs", icon: "🎙️", color: "blue" },
    linkedin: { name: "LinkedIn", icon: "💼", color: "blue" },
    twitch: { name: "Twitch", icon: "🎮", color: "purple" },
    kick: { name: "Kick", icon: "🥊", color: "green" },
    spotify: { name: "Spotify", icon: "🎧", color: "green" },
    facebook: { name: "Facebook", icon: "👍", color: "blue" },
    pinterest: { name: "Pinterest", icon: "📌", color: "red" },
    bluesky: { name: "Bluesky", icon: "🦋", color: "blue" },
    telegram: { name: "Telegram", icon: "✈️", color: "blue" },
    bereal: { name: "BeReal", icon: "📷", color: "black" },
    medium: { name: "Medium", icon: "📝", color: "black" },
    etsy: { name: "Etsy", icon: "🛒", color: "orange" },
    onlyfans: { name: "OnlyFans", icon: "💎", color: "blue" },
    patreon: { name: "Patreon", icon: "🎨", color: "orange" },
    dating: { name: "Dating", icon: "💕", color: "pink" },
    amazon: { name: "Amazon", icon: "📦", color: "orange" },
    forocoches: { name: "Forocoches", icon: "🚗", color: "blue" },
    podcast: { name: "Podcast", icon: "🎙️", color: "purple" },
    threads: { name: "Threads", icon: "🧵", color: "black" },
    email: { name: "Email", icon: "📧", color: "gray" },
    general: { name: "General", icon: "🔧", color: "gray" },
};

/**
 * Get the total count of official tools.
 */
export function getOfficialToolsCount(): number {
    return OFFICIAL_TOOLS.length;
}

/**
 * Get all unique platforms from the tools index.
 */
export function getAllPlatforms(): string[] {
    return [...new Set(OFFICIAL_TOOLS.map((tool) => tool.platform))];
}

/**
 * Get tools for a specific platform.
 */
export function getToolsByPlatform(platform: string): OfficialTool[] {
    return OFFICIAL_TOOLS.filter((tool) => tool.platform === platform);
}
