export const youtubeCommunityPostGenerator = {
    title: "YouTube Community Post Generator",
    description: "Engage your subscribers with polls, updates, and questions generated by AI.",
    form: {
        topic: "Post Topic",
        topicPlaceholder: "e.g., New video announcement, Asking for feedback...",
        type: "Post Type",
        types: {
            update: "Channel Update",
            poll: "Poll Question",
            question: "Question for Subscribers",
            behindTheScenes: "Behind the Scenes",
            promotion: "Video Promotion",
        },
        tone: "Tone",
        tones: {
            engaging: "Engaging",
            excited: "Excited",
            professional: "Professional",
            casual: "Casual",
            humorous: "Humorous",
        },
        language: "Language",
        generate: "Generate Post",
        generating: "Writing Post...",
        useAgain: "Write Another Post",
        error: {
            emptyTopic: "Please enter a topic",
        },
    },
    result: {
        title: "Generated Post",
        copy: "Copy Post",
        copied: "Copied!",
        success: "Post copied to clipboard!",
    },
    topFeatures: {
        title: "Why Use Our Community Post Generator?",
    },
    features: {
        feature1: {
            title: "Boost Engagement",
            description: "Create posts that encourage likes, comments, and votes.",
        },
        feature2: {
            title: "Various Formats",
            description: "Supports polls, updates, questions, and more.",
        },
        feature3: {
            title: "Tone Control",
            description: "Match the voice of your channel perfectly.",
        },
        feature4: {
            title: "Time Saver",
            description: "Keep your community active without spending hours writing.",
        },
    },
    hero: {
        subtitle: "Connect with Your Audience",
        description: "The Community Tab is a powerful way to stay connected with your subscribers between uploads. Our AI helps you write engaging posts that keep your audience interested.",
    },
    howItWorks: {
        title: "How It Works",
        step1: {
            title: "Choose Type",
            description: "Select the type of post you want to create.",
        },
        step2: {
            title: "Enter Topic",
            description: "What do you want to tell your subscribers?",
        },
        step3: {
            title: "Get Post",
            description: "Receive a perfectly formatted post ready to publish.",
        },
    },
    faq: {
        title: "Frequently Asked Questions",
        q1: "What is the Community Tab?",
        a1: "It's a feature on YouTube that lets creators interact with their audience using text, images, polls, and videos.",
        q2: "Who can use the Community Tab?",
        a2: "Most channels with over 500 subscribers have access to it.",
        q3: "Can I add images to these posts?",
        a3: "Yes! The AI generates the text, and you can attach images or polls when you post on YouTube.",
        q4: "How often should I post?",
        a4: "Posting 1-3 times a week helps keep your channel active and your audience engaged.",
        q5: "Is it free?",
        a5: "Yes, generate unlimited community posts for free.",
    },
    relatedTools: {
        title: "More YouTube Tools",
    },
};
